version: '3'

services:
    api:
        build: ./api
        container_name: api
        restart: always
        volumes:
          - ./api/:/app
        depends_on:
          - db
        expose:
          - 9000
        depends_on:
          - redis

    redis:
        image: redis

    ui:
        build: ./ui
        container_name: ui
        restart: always
        expose:
            - 80

    nginx:
        build: ./nginx
        container_name: nginx
        restart: always
        ports:
            - "8000:8000"
            - "8001:80"