version: '3.2'

services:
    api:
        build: ./api
        environment:
            PGHOST: db
            PGUSER: postgres
            PGPASSWORD: postgres
            PGDATABASE: postgres_db
            PGDATABASETEST: postgres_test
            PGPORT: 5432
        container_name: api
        restart: always
        volumes:
          - ./api/:/app
        depends_on:
          - db
          - redis
        expose:
          - 9000

    redis:
        image: redis

    db:
        image: postgres:11
        environment:
            POSTGRES_USER: postgres
            POSTGRES_PASSWORD: postgres
            PGDATA: /var/lib/postgresql/data/pgdata
        restart: always
        ports:
            - "5432:5432"
        volumes:
            - ./data/:/var/lib/postgresql/data/:z

    ui:
        build: ./ui
        container_name: ui
        restart: always
        expose:
            - 80

    nginx:
        build: ./nginx
        container_name: nginx
        restart: always
        depends_on:
          - api
          - ui
        ports:
            - "8000:8000"
            - "8001:80"