version: '3'

services:
    api:
        build: ./api
        container_name: api
        restart: always
        volumes:
          - ./api/:/app
        depends_on:
          - db
        expose:
          - 9000
        depends_on:
          - redis

    redis:
        image: redis

    db:
        image: postgres:11
        environment:
            POSTGRES_USER: postgres
            POSTGRES_PASSWORD: postgres
            PGDATA: /var/lib/postgresql/data/pgdata
        restart: always
        ports:
            - "5432:5432"
        volumes:
            - ./data/:/var/lib/postgresql/data/:z

    ui:
        build: ./ui
        container_name: ui
        restart: always
        expose:
            - 80

    nginx:
        build: ./nginx
        container_name: nginx
        restart: always
        ports:
            - "8000:8000"
            - "8001:80"